pelias/docker

- projects/france/.env
- projects/france/README.md
- projects/france/docker-compose.yml
- projects/france/elasticsearch.yml
- projects/france/pelias.json
This PR add a full France example :)
> Add France example

- README.md
- cmd/test.sh
- projects/los-angeles-metro/README.md
- projects/los-angeles-metro/docker-compose.yml
- projects/los-angeles-metro/pelias.json
- projects/los-angeles-metro/test_cases/search_venue.json
- projects/portland-metro/README.md
- projects/portland-metro/docker-compose.yml
- projects/portland-metro/pelias.json
- projects/portland-metro/test_cases/search_address.json
- projects/portland-metro/test_cases/search_venue.json
> fuzzy_tester: add acceptance test runner

- projects/portland-metro/pelias.json
If this file comes back, we can add it again. For now it adds a lot of log noise.
Connects #19
> Remove Cherriots download

- README.md
https://www.youtube.com/watch?v=ustXRPke9lM
> the the --> the

- projects/san-jose-metro/pelias.json
I forgot to update the OSM filename after updating the metro extract.
> Updated OSM filename

- projects/san-jose-metro/pelias.json
Caused an error to be thrown during setup.
> Fix JSON formatting bug

- projects/belgium/.env
- projects/belgium/README.md
- projects/belgium/docker-compose.yml
- projects/belgium/elasticsearch.yml
- projects/belgium/pelias.json
Hi
I based the config file on the one from France, the readme and docker-compose file were copied too.
I tested it locally and seems to work fine (I didn't tested the geonames).
Thanks
> Add Belgium project

- projects/singapore/.env
- projects/singapore/README.md
- projects/singapore/docker-compose.yml
- projects/singapore/pelias.json
This PR adds a docker project for the Singapore region
> add singapore project

- projects/jamaica/.env
- projects/jamaica/README.md
- projects/jamaica/docker-compose.yml
- projects/jamaica/pelias.json
- projects/jamaica/test_cases/search_address.json
- projects/jamaica/test_cases/search_venue.json
Create a project for Jamaica, it is intended as an example to other countries in the caribbean.
A few addresses were added as test cases demonstrating what is working and what isn't.
> Added jamaica

- projects/planet/README.md
Fixes https://github.com/pelias/docker/issues/90
> Add submodule documentation to Planet project

- cmd/download.sh
This was missed in https://github.com/pelias/docker/pull/50
> Add geonames download command

- projects/brazil/.env
- projects/brazil/README.md
- projects/brazil/docker-compose.yml
- projects/brazil/pelias.json
Note: I did not provide tests. Please tell me if it's a requirement.
> feat: add Brazil project

- projects/netherlands/.env
- projects/netherlands/README.md
- projects/netherlands/docker-compose.yml
- projects/netherlands/elasticsearch.yml
- projects/netherlands/pelias.json
I've added The Netherlands as a example project. I used the Belgium project as a starting point.
> Added example project for The Netherlands

- images/elasticsearch/6.8.3/Dockerfile
- images/elasticsearch/6.8.3/elasticsearch.yml
This is an initial attempt at an ES6 Pelias docker image
Connects https://github.com/pelias/pelias/issues/719
> Add Elasticsearch 6 docker image

- projects/australia/pelias.json
- projects/belgium/pelias.json
- projects/brazil/pelias.json
- projects/france/pelias.json
- projects/jamaica/pelias.json
- projects/los-angeles-metro/pelias.json
- projects/netherlands/pelias.json
- projects/north-america/pelias.json
- projects/planet/pelias.json
- projects/portland-metro/pelias.json
- projects/san-jose-metro/pelias.json
- projects/singapore/pelias.json
- projects/south-africa/pelias.json
> Remove textAnalyzer from configs, no more used

- projects/singapore/pelias.json
- projects/singapore/test_cases/search_venue.json
minor fixes to the `Singapore` project to make it more consistent with the other projects:
- remove log trace command
- add some basic test_cases
> singapore: minor fixes

- projects/australia/docker-compose.yml
- projects/australia/pelias.json
- projects/belgium/docker-compose.yml
- projects/belgium/pelias.json
- projects/brazil/docker-compose.yml
- projects/brazil/pelias.json
- projects/france/docker-compose.yml
- projects/france/pelias.json
- projects/jamaica/docker-compose.yml
- projects/jamaica/pelias.json
- projects/los-angeles-metro/docker-compose.yml
- projects/los-angeles-metro/pelias.json
- projects/netherlands/docker-compose.yml
- projects/netherlands/pelias.json
- projects/planet/docker-compose.yml
- projects/planet/pelias.json
- projects/portland-metro/docker-compose.yml
- projects/portland-metro/pelias.json
- projects/san-jose-metro/docker-compose.yml
- projects/san-jose-metro/pelias.json
- projects/singapore/docker-compose.yml
- projects/singapore/pelias.json
- projects/south-africa/docker-compose.yml
- projects/south-africa/pelias.json
this PR updates all the projects to use elasticsearch v6
> set elasticsearch6 as default

- projects/north-america/docker-compose.yml
- projects/north-america/pelias.json
various updates to North America project:
- set `DOCKER_USER`
- set explicit Elasticsearch version
- add Geonames config (not sure why this was missing?)
I've simply done a diff against the `Planet` configs and updated `North America` accordingly.
> various updates to north america project

- projects/south-america/.env
- projects/south-america/README.md
- projects/south-america/docker-compose.yml
- projects/south-america/pelias.json
I created a South America project and would like to know if you are interested to keep it in your main repository.
I created an issue (165) and it will fix it if this PR is accepted.
We are already using this project in production.
We based the South America project from the Brazil project. I added the openaddress of the other countries and the whosonfirst of the South America.
---
- Fixes pelias/docker#165
> South America Project

- projects/norway/.env
- projects/norway/README.md
- projects/norway/docker-compose.yml
- projects/norway/elasticsearch.yml
- projects/norway/pelias.json
:wave: I did some work for the awesome Pelias project and would love for everyone to have a look at it and provide feedback. 
---
- Add Norway to the projects folder
---
---
Do a build :-)
> add project for norway

- projects/germany/.env
- projects/germany/README.md
- projects/germany/docker-compose.yml
- projects/germany/elasticsearch.yml
- projects/germany/pelias.json
README
---
This adds Germany - a whole country, which is good - as a project for use for Pelias geolocation. (Personally speaking, I wanted to setup up a Twitter bot that used Pelias.)  
---
I added some basic configuration for German openaddresses data (which, granted, is somewhat sparse) as well as the relevant OpenStreetMap ID. 
---
I did some basic manual tests and queries, though have not added them as docker tests. I can happily add some if required.
> Add Germany as a project

- projects/germany/pelias.json
> Add `Kreis Viersen` to openaddresses import files

- projects/poland/.env
- projects/poland/README.md
- projects/poland/docker-compose.yml
- projects/poland/elasticsearch.yml
- projects/poland/pelias.json
- projects/poland/test_cases/search_address.json
---
* add Poland as a set of configuration files
---
New folder in projects with configuration :
- pbf location for OSM
- openaddress file list from [pl](https://github.com/openaddresses/openaddresses/tree/master/sources/pl) directory
- WOF : used [85633723](https://spelunker.whosonfirst.org/id/85633723/)
---
`pelias test run`
> feat(poland): Add Poland as a project

- README.md
Adding an example from a running instance of the Libpostal Service (whosonfirst/go-whosonfirst-libpostal server) for use by Pelias. More details: https://github.com/pelias/libpostal-service#example-usage
---
---
---
> Adding example for Libpostal Service

- projects/italy/.env
- projects/italy/README.md
- projects/italy/docker-compose.yml
- projects/italy/elasticsearch.yml
- projects/italy/pelias.json
:wave: I added a project for Italy autocompletions.
---
I needed Italy autocompletions for an internal demo
---
> Add Italy project

- projects/lithuania/.env
- projects/lithuania/README.md
- projects/lithuania/docker-compose.yml
- projects/lithuania/elasticsearch.yml
- projects/lithuania/pelias.json
---
* add Lithuania as a set of configuration files
---
New folder in projects with configuration :
* pbf location for OSM
* openaddress file list from [lt](https://github.com/openaddresses/openaddresses/tree/master/sources/lt) directory
* WOF : used [85633269](https://spelunker.whosonfirst.org/id/85633269/)
---
Follow instructions in README.md
> Add project for Lithuania

- projects/israel/.env
- projects/israel/README.md
- projects/israel/docker-compose.yml
- projects/israel/elasticsearch.yml
- projects/israel/pelias.json
Hello everyone :)
I've added a project for the Israel area. 
The new project was tested with the query:  http://localhost:4000/v1/search?text=TelAviv
> new project : Israel

- projects/kyrgyzstan/.env
- projects/kyrgyzstan/README.md
- projects/kyrgyzstan/docker-compose.yml
- projects/kyrgyzstan/elasticsearch.yml
- projects/kyrgyzstan/pelias.json
Added Kyrgyzstan country to docker/projects/
> Added Kyrgyzstan country

- projects/north-america/README.md
Found while browsing the docs (also, thanks for the docs!)
> Fix typo in readme

- .github/workflows/elasticsearch-image-builder.yml
- images/elasticsearch/7.17.15/Dockerfile
- images/elasticsearch/7.17.15/elasticsearch.yml
this is a DRAFT workflow for automagically building elastic docker images
> CI: github actions workflow for building elastic docker images

- .github/workflows/elasticsearch-image-builder.yml
disable image-builder workflow due to https://github.com/pelias/ci-tools/issues/13
> actions: disable image-builder workflow
