projects/france/pelias.json
projects/los-angeles-metro/pelias.json
projects/portland-metro/pelias.json
projects/south-africa/pelias.json

The url to the pip service in the example projects pelias.json config files was `http://pip-service:4200`. In the docker-compose.yml files, the name of the service is `pip` (not `pip-service`).
This PR changes `api.services.pip.url` to `http://pip:4200`.
Fixes #7

Fix pip path in project pelias.json files

---

cmd/elastic.sh
cmd/prepare.sh

NPM creates an extra layer of processes in containers which [do not properly forward signals](https://github.com/npm/npm/issues/4603). This
can cause problems starting/stopping containers quickly.
Additionally NPM tries to write to the filesystem as part of its self-update check. We would like to move to read only root container filesystems (using `read_only: true` in docker-compose.yml), so the easiest way to work around this NPM "feature" is to avoid using NPM.

Avoid using NPM in scripts

---

projects/france/docker-compose.yml
projects/los-angeles-metro/docker-compose.yml
projects/portland-metro/docker-compose.yml
projects/south-africa/docker-compose.yml

We have some settings in our docker-compose.yml files that are from when we did things quite differently.
Previously, we built the libpostal_baseimage image directly as part of
our Docker setup projects. This required setting it as a "dependency" of
other images. That's no longer required, and having that `dependency`
setting is causing an extra container to be launched, after which it
does nothing and shuts down.
Additionaly, we used to store libpostal training data in a separate
filesystem. It's now baked into the `libpostal_baseimage` image, so all
those settings are no longer required.

Remove out of date libpostal settings

---

projects/portland-metro/blacklist/osm.txt
projects/portland-metro/docker-compose.yml
projects/portland-metro/pelias.json

This removes the problematic PDX record from OSM (which has a centroid
that is unhelpful for routing, with no clear way to fix).

Add example of using blacklist functionality

---

projects/france/docker-compose.yml
projects/france/pelias.json
projects/los-angeles-metro/docker-compose.yml
projects/los-angeles-metro/pelias.json
projects/portland-metro/docker-compose.yml
projects/portland-metro/pelias.json
projects/south-africa/docker-compose.yml
projects/south-africa/pelias.json

This image, from [pelias/libpostal-service](https://github.com/pelias/libpostal-service) gives us a bit more control and consistency over how the libpostal-service is run.
Benefits include:
- smaller download footprint since it shares the pelias/libpostal_baseimage download with the interpolation service
- non-root `pelias` user and other features common to pelias/baseimage
- default port number consistent with other Pelias services

Use new pelias/libpostal-service Docker image

---

cmd/download.sh
cmd/import.sh

NPM can cause issues when running in docker containers, such as:
- requiring write access to the root filesystem and printing a large annoying warning if it doesn't have it
- not passing signals on to process it starts, making it take longer to gracefully kill containers
Now that all our Docker images have their own `start` and `download` scripts to serve as more reliable entry points, we can remove all calls to `npm` by the `pelias` script.
Connects https://github.com/pelias/pelias/issues/745

Remove all calls to npm in `pelias` binary

---

README.md
projects/france/.env
projects/france/docker-compose.yml
projects/los-angeles-metro/.env
projects/los-angeles-metro/docker-compose.yml
projects/portland-metro/.env
projects/portland-metro/docker-compose.yml
projects/south-africa/.env
projects/south-africa/docker-compose.yml

By default, all Pelias images now have a user called `pelias` with UID 1000. However, running as a different UID may be best for different people, depending on their system setup.
By setting the default in `.env` and using it in `docker-compose.yml`, we can allow people running Pelias to use whatever non-root user is best for them.
Connects https://github.com/pelias/baseimage/pull/2

Allow configuring container process UID

---

images/elasticsearch/5.6.12/Dockerfile

I missed this setting in https://github.com/pelias/docker/pull/24
Having this set in the image avoids having to remember to set it all the time during dev :)

set discovery.type in Dockefile

---

projects/australia/.env
projects/australia/README.md
projects/australia/docker-compose.yml
projects/australia/pelias.json
projects/australia/test_cases/search_address.json
projects/australia/test_cases/search_venue.json

Australia is a perfect mid-sized test case for Pelias: it comes in at a total of about 15 million records, and has good coverage thanks to the [G-NAF](https://www.psma.com.au/products/g-naf) dataset which has been imported into OpenAddresses and covers nearly all Australian addresses.
Despite the high record count, the OSM extract is relatively small, which means there won't be any problems running the `pbf streets` polyline extractor, which is fast but can't handle PBFs over 1GB or so.

Add Australia project

---

README.md

As part of our switch to running Pelias containers as non-root users (https://github.com/pelias/pelias/issues/745), it's now important that the directory used for Pelias data has proper permissions.
It's very easy for the data directory to end up being writable either only by the `root` user or a user different than the one running in the Pelias containers, in which case nothing will work .
This line in the example script should make things right.

fix(docs): Add line setting proper permissions in README

---

README.md
projects/australia/docker-compose.yml
projects/australia/pelias.json
projects/france/docker-compose.yml
projects/france/pelias.json
projects/los-angeles-metro/docker-compose.yml
projects/los-angeles-metro/pelias.json
projects/portland-metro/docker-compose.yml
projects/portland-metro/pelias.json
projects/south-africa/docker-compose.yml
projects/south-africa/pelias.json

Depends on https://github.com/pelias/schema/pull/323, please merge that first and wait for a new version of the `pelias/schema:latest` branch to be published to dockerhub.
Many projects are also based off the experimental `pelias/schema:portland-synonyms` image, so that image will need to pull in master after 323 is merged and then republished to dockerhub.

switch projects to use elasticsearch 5.x

---

cmd/elastic.sh
projects/australia/pelias.json

This puts in a very basic fix for ES5 related startup issues as described in #33.
Additionally, it fixes #34 by limiting how long `pelias elastic wait` will wait for Elasticsearch to start. The limit is 60 seconds.

Fix es5 startup

---

images/elasticsearch/5.6.12/Dockerfile

In order to upload snapshots to s3, the `repository-s3` plugin is required.
A new image with this change has been pushed to `pelias/elasticsearch:5.6.12` on hub.docker.com

feat(es5-image): Add `repository-s3` plugin

---

cmd/docker.sh

This is required in order to see color output from the acceptance tests.
@missinglink, do you recall why we originally disabled TTYs?

feat(docker): Enable TTY when running docker containers

---

cmd/import.sh

Use the parallel build script from OpenAddresses to allow for multiple parallel builds.
This feature is experimental for now, and will not yet be documented.

feat(pelias-cmd): Support OpenAddresses paralell imports

---

cmd/elastic.sh

With Elasticsearch 5, proper permissions (by default for user 1000) must
be set on the data directory on the host system.
Users have consistently run the `pelias` helper script as users with a
different UID than 1000, or the one configured in `.env` (usually root),
so this change uses `chown` to set ownership of the Elasticsearch data
directory.
Connects https://github.com/pelias/docker/issues/33
Connects https://github.com/pelias/docker/issues/53

docker: run chown on Elasticsearch directory

---

cmd/elastic.sh

In https://github.com/pelias/docker/pull/55 we added a `chown` line that attempts to set proper permissions on the Elasticsearch data directory.
`chown` can generally only be run as root, so this PR adds handling for the common case where `chown` fails.
In general, either the pelias CLI is run as root, and the `chown` will succeed, or the CLI is run as the same user the Docker container processes will run as. In this case the `mkdir` on the preceding line will set up the directory with proper ownership.
We can't really do anything in an automated way to handle people running the Pelias CLI as a different, non-root, user than the one they want the containers to run with, so I think this is the best we can do.
This will be even more useful once https://github.com/pelias/docker/pull/62 is …

fix(cli): Handle chown failures when running as non-root

---

images/elasticsearch/5.6.12/Dockerfile
projects/portland-metro/docker-compose.yml

This sets some more permissive permissions on various directories,
files, and executables used in the Elasticsearch 5 docker image.
It allows the user the container processes run under to be changed from
the default of 1000, which helps keep things consistent with the rest of
the Pelias containers.
Fixes https://github.com/pelias/docker/issues/46

fix(ES image): Allow running Elasticsearch 5 container as any user

---

cmd/docker.sh

The Pelias CLI was relying on the fact that a command such as `pelias
elastic start`, which only starts one container, was run before commands such as `pelias import all`, which can start many containers very quickly.
This PR adds a call to `docker network create ...` before starting any containers, which removes the possibility of multiple duplicate networks being created.
This prevents issues with errors such as:
```
ERROR: 5 matches found based on name: network pelias_default is
ambiguous
```
when running commands on the Pelias CLI.
Connects https://github.com/pelias/docker/issues/51

fix(net): Safely initialize Docker network

---

cmd/download.sh
cmd/import.sh
projects/australia/docker-compose.yml
projects/france/docker-compose.yml
projects/los-angeles-metro/docker-compose.yml
projects/north-america/docker-compose.yml
projects/planet/docker-compose.yml
projects/portland-metro/docker-compose.yml
projects/portland-metro/pelias.json
projects/san-jose-metro/docker-compose.yml
projects/south-africa/docker-compose.yml

The new [csv-importer](https://github.com/pelias/csv-importer) is built to import arbitrary custom data into Pelias from CSV files.
This PR includes it in the Pelias CLI and all project `docker-compose.yml` files.
The importer is designed to do nothing if there's no configuration block in `pelias.json`, and such a configuration is only added for the Pelias metro project, with a small example CSV used in that case.

Add example of using CSV importer

---

cmd/elastic.sh

As of https://github.com/pelias/schema/pull/340, it's required to use the `./bin/create_index` entrypoint script to use pelias/schema to create an Elasticsearch index.
This entrypoint script sets proper command line flags, and generally fits the pattern of our own custom scripts to set reasonable defaults where required.

fix(schema): Use entrypoint script to create ES index

---

projects/france/docker-compose.yml
projects/los-angeles-metro/docker-compose.yml
projects/portland-metro/docker-compose.yml

Now that https://github.com/pelias/schema/pull/310 has been merged, using the `portland-synonyms` branch is no longer required.
Fixes #67

Use schema master branch everywhere

---

images/elasticsearch/5.6.12/elasticsearch.yml

The default was increased from 50 to 200 for ES5, but that's not enough
to allow all importers to run simultaneously on a planet sized import.
1000 is the same value we've used with ES2 and should continue to work
well. We haven't experienced any negative side effects to having this
set very high for smaller imports.
In theory, running an import on a very CPU constrained server would use
more memory storing things in the queue, but that hasn't been observed
to be a problem yet.
Connects https://github.com/pelias/pelias/issues/461

feat(ES5): Increase bulk import queue_size to 1000

---

README.md
projects/planet/README.md

* Improve recommendations around full planet builds, as we have been running them successfully in Docker for a while now
* Add emphasis to Mac OSX requirements, as people continue to miss them.

Documentation updates

---

images/elasticsearch/2.4/Dockerfile
images/elasticsearch/2.4/elasticsearch.yml

Similar to https://github.com/pelias/docker/pull/71, its helpful to set the bulk import queue size to much larger than the default (50 for ES 2.4).
Without this setting, imports when running multiple importers can easily overwhelm Elasticsearch and fail.

Set default bulk queue size for ES 2.4 image

---

lib/env.sh

If the variable DATA_DIR is already set the declaration of it via `.env` may be
ignored.
This prints only a warning rather than to unset the variable. Thus no documentation is broken, staying backward compatible.
It's interesting to debug the script like with `bash -x pelias prepare all` to see that there are *two values* for *one key* if the DATA_DIR is set as a variable (via `.env`) and outside of the `.env`.
Resolves #93.

Warn if DATA_DIR is already set

---

projects/planet/docker-compose.yml
projects/planet/pelias.json

This is the last project not using ES5, and marks the completion of https://github.com/pelias/pelias/issues/461!
All our testing shows that ES5 performs well, with good query results and about 10% better throughput and 10% lower request latency.

Use ES5 for planet build

---

projects/france/pelias.json

I added the France country id to wof because who's on first *France Empire* have no any result for the *Bretagne* Region 
This PR is to be able to retrieve all locality from Bretagne 
Fixes https://github.com/pelias/pelias/issues/798

Add the coutry France to WOF to get Bretagne Results

---

projects/australia/docker-compose.yml
projects/belgium/docker-compose.yml
projects/france/docker-compose.yml
projects/jamaica/docker-compose.yml
projects/los-angeles-metro/docker-compose.yml
projects/north-america/docker-compose.yml
projects/planet/docker-compose.yml
projects/san-jose-metro/docker-compose.yml
projects/south-africa/docker-compose.yml

I encountered permission errors with the ES container and debugging I noticed that the user var was not passed. This fixes it.
Context: https://github.com/pelias/docker#variable-docker_user

Set DOCKER_USER for Elasticsearch as well.

---

images/elasticsearch/5.6.12/Dockerfile
images/elasticsearch/5.6.12/elasticsearch.yml

The X-Pack extensions to Elasticsearch are proprietary addons for
additional functionality, none of which is needed by Pelias.
In the past, we've made due with disabling some of them by environment
variable, however that still leaves them present to emit scary warnings
about licenses. These warnings probably are ok to ignore, again since
Pelias does not use any X-Pack features.
However, its best to avoid scary warnings where possible, so this change
removes the X-Pack plugin completely.
Fixes https://github.com/pelias/docker/issues/110

feat(elasticsearch-5): Remove X-Pack extension

---

README.md

It will help to know which folders can be safely removed after the build is complete.
With my basic experimentation, these folders seemed OK to delete once the full import into elastic search is done, but maybe I missed something so I'm suggesting this change to both improve the documentation and validate that it's safe to do.

added data cleanup

---

images/elasticsearch/7.4.0/Dockerfile
images/elasticsearch/7.4.0/elasticsearch.yml

This is the first step in supporting Elasticsearch 7.
At this time, Pelias does not work out of the box on ES7, but with a Docker image ready to go, we can begin testing changes for compatibility.
This Dockerfile and config is identical to the ES6 Docker image, except for changing the version, and making one update to the `elasticsearch.yml`:
In ES7, the bulk thread pool is removed, and both bulk and non-bulk operations go through a single
[write](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-threadpool.html#modules-threadpool) thread pool.
For Pelias we have found increasing the queue size of this thread pool is useful to ensure imports can succeed without errors, so the configuration file has been updated accordingly.
Connects …

Add Elasticsearch 7.4.0 Docker image

---

README.md
cmd/elastic.sh

this PR adds two new common elasticsearch commands:
```
elastic   info                     display elasticsearch version and build info
elastic   stats                    display a summary of doc counts per source/layer
```

elastic: add two new elasticsearch commands

---

projects/australia/pelias.json
projects/belgium/pelias.json
projects/brazil/pelias.json
projects/france/pelias.json
projects/jamaica/pelias.json
projects/los-angeles-metro/pelias.json
projects/netherlands/pelias.json
projects/north-america/pelias.json
projects/planet/pelias.json
projects/portland-metro/pelias.json
projects/san-jose-metro/pelias.json
projects/singapore/pelias.json
projects/south-africa/pelias.json

following on from https://github.com/pelias/docker/pull/144 this PR updates `pelias.json` settings in order to produce ES indices compatible with versions 6 & 7
in order to continue supporting elasticsearch@5 during our deprecation window, we are still using the type name "doc" by default.
using "doc" ensures **forward** compatibility between elasticsearch versions 5 & 6, but does not work with 7.
since the configs here are already set to build on version 6 (which isn't **backwards** compatible with 5), we can use this setting to ensure that new indices built are done using the type named "_doc" (note the underscore).
this will ensure that indices are compatible with 6 & 7 and that users building after this change will not suffer from the breaking change introduced by a type name change …

update pelias.json settings in order to produce ES indices compatible with versions 6+7

---

cmd/elastic.sh

Prior to this PR we would exit 0 with the message "Elasticsearch up!" even if the cluster status was red.
This PR changes the `elastic_status` command to target the [cluster health API](https://www.elastic.co/guide/en/elasticsearch/reference/current/cluster-health.html) using the param `wait_for_status=yellow`
One easy way to cause a red status is to start an elasticsearch server on top of an index which was created with a previous version and is no longer compatible.

elastic_wait: wait for yellow

---

images/elasticsearch/6.8.5/Dockerfile
images/elasticsearch/7.4.2/Dockerfile

This issue came in yesterday via a Geocode Earth support request.
When customizing the `user:group` settings using the env var `DOCKER_USER=` the new `pelias/elasticsearch:6.8.5` image fails to start due to permission errors.
More accurately it works fine if only specifying a `user` such as `DOCKER_USER=500` but fails when specifying a `group` such as `DOCKER_USER=500:500`.
The issue can be reproduced with the following command:
```bash
docker run --rm -it -u 500:500 pelias/elasticsearch:6.8.5
```
This PR updates permissions on the `./logs` and `./data` directories as not having write permission on either of these directories will cause a fatal error upon boot.

elasticsearch 6 image fails to start when custom groups used

---

projects/los-angeles-metro/pelias.json

---
When downloading data in the `los-angeles-metro` project, the attempt to download gtfs_rail.zip fails (#152).
---
Changed the URL to reference the new github repo that now contains gtfs_rail.zip.
---
`pelias download all` should now download gtfs_rail.zip without error.

Update LACMTA gtfs_rail URL. Fixes #152.

---

README.md

we've had a couple of reports that our `docker-compose.yml` files don't work on older versions of `docker-compose`.
this PR updates the prerequisites documentation slightly to indicate that a "modern" version is required.
I'm not sure exactly which minimum versions are required, so the general advice is to use something that existed at the time the code/config which it's consuming was written.
related: https://github.com/pelias/docker/issues/155, https://github.com/pelias/docker/issues/2

docs(readme): link to docker and docker-compose changelogs

---

projects/australia/pelias.json
projects/belgium/pelias.json
projects/brazil/pelias.json
projects/france/pelias.json
projects/jamaica/pelias.json
projects/los-angeles-metro/pelias.json
projects/netherlands/pelias.json
projects/north-america/pelias.json
projects/planet/pelias.json
projects/portland-metro/pelias.json
projects/san-jose-metro/pelias.json
projects/singapore/pelias.json
projects/south-africa/pelias.json

Now that we have merged https://github.com/pelias/config/pull/122 and associated PRs to add Elasticsearch 7 support to Pelias master branches, we no longer need to override the `typeName` config option in project `pelias.json` configration.
This reverts commit acc4202eee969e315dac82d2e775e87b03101f91.
Connects https://github.com/pelias/pelias/issues/831

Remove typeName configuration option

---

projects/australia/docker-compose.yml
projects/australia/pelias.json
projects/belgium/docker-compose.yml
projects/belgium/pelias.json
projects/brazil/docker-compose.yml
projects/brazil/pelias.json
projects/france/docker-compose.yml
projects/france/pelias.json
projects/jamaica/docker-compose.yml
projects/jamaica/pelias.json
projects/los-angeles-metro/docker-compose.yml
projects/los-angeles-metro/pelias.json
projects/netherlands/docker-compose.yml
projects/netherlands/pelias.json
projects/north-america/docker-compose.yml
projects/north-america/pelias.json
projects/planet/docker-compose.yml
projects/planet/pelias.json
projects/portland-metro/docker-compose.yml
projects/portland-metro/pelias.json
projects/san-jose-metro/docker-compose.yml
projects/san-jose-metro/pelias.json
projects/singapore/docker-compose.yml
projects/singapore/pelias.json
projects/south-africa/docker-compose.yml
projects/south-africa/pelias.json

We've done a lot of testing on ES7 and are now pretty confident that it can be rolled out to all projects, which will help us gather even more data about how well it works.
Connects https://github.com/pelias/pelias/issues/831

Use Elasticsearch 7.5.1 across all projects

---

cmd/prepare.sh

disable TTY for prepare scripts to avoid unsightly buffering

disable TTY for prepare scripts to avoid unsightly buffering

---

cmd/download.sh

following on from https://github.com/pelias/docker/pull/184 this PR fixes the same thing for the `download all` command

disable TTY for prepeare scripts to avoid unsightly buffering

---

projects/australia/pelias.json
projects/belgium/pelias.json
projects/brazil/pelias.json
projects/france/pelias.json
projects/jamaica/pelias.json
projects/los-angeles-metro/pelias.json
projects/netherlands/pelias.json
projects/north-america/pelias.json
projects/planet/pelias.json
projects/portland-metro/pelias.json
projects/san-jose-metro/pelias.json
projects/singapore/pelias.json
projects/south-africa/pelias.json
projects/south-america/pelias.json

Now that the Who's on First downloader defaults to using SQLite downloads and supports country-specific bundles thanks to https://github.com/pelias/whosonfirst/pull/487, we can start using that new functionality.
This PR sets the `imports.whosonfirst.countryCode` property appropriately across all our current projects.
This should not only help make all imports quite a bit faster, but it will require much less disk space for everyone!
Since we're now sponsoring the Who's on First downloads here at Geocode Earth, the bandwidth savings also make us happy :)
Along the way I made a few minor changes to remove some deprecated config options like `importVenues` and `sqlite`.

Add `countryCode` property to WOF configuration

---

projects/belgium/pelias.json

Fixes https://github.com/pelias/docker/issues/193
Include the official data from the 3 regions (updated regurarly, full coverage) in Belgium, see also https://github.com/openaddresses/openaddresses/pull/4582

Update pelias.json for Belgium

---

README.md

this PR extends upon https://github.com/pelias/docker/pull/186 and resolves https://github.com/pelias/docker/issues/196
@caduguedess rightly points out that if the install instructions are followed then it's possible to end up with two clones of the repo in different directories.
this PR ensures that the same method is suggested for both sections.

resolve inconsistency between differing install directory instructions

---

cmd/import.sh

Set $CSV_PARALLELISM to a number to use.
Without this variable set, there will be no behavior change.

Allow parallelizing the CSV importer

---

projects/los-angeles-metro/pelias.json
projects/portland-metro/pelias.json

Projects with `whosonfirst.importVenues` on `pelias.config` are falling with: 
```
Error: "imports.whosonfirst.importVenues" is not allowed
```
I believe it's related to https://github.com/pelias/config/pull/128.
This PR removes `whosonfirst.importVenues` from _portland-metro_ and _los-angeles-metro_ projects.

fix(pelias.json): remove whosonfirst.importVenues from projects

---

projects/portland-metro/test_cases/search_address.json
projects/portland-metro/test_cases/search_venue.json

Most of the test failures have been around for a while, and they actually correspond to tests for cases that Pelias can't currently handle, such as wildly incorrect street names or city names.
Fixes https://github.com/pelias/docker/issues/204

Update expectations for portland acceptance tests

---

README.md

People often ask how long larger builds will take, so this PR includes some basic info and links to more details.
Closes https://github.com/pelias/docker/issues/160

Add 'How long will it take?' docs section

---

README.md

While other `pelias` commands should not be run with `sudo`, `sudo` will generally be required to create a symbolic link in `/usr/local/bin/` as described in our quickstart script.
This change adds `sudo` to that command and clarifies that it's the only part of the quickstart script that should use `sudo`.
Connects https://github.com/pelias/docker/issues/214

Clarify that `ln` command may require sudo

---

projects/norway/.env
projects/portland-metro/.env

a couple of `DOCKER_USER` lines have crept in to the .env files since merging https://github.com/pelias/docker/pull/220

remove DOCKER_USER lines from project .env files

---

images/elasticsearch/7.5.1/elasticsearch.yml

Complex configurations with many synonyms can run into problems with
Elasticsearch throwing an error about exceeding the `max_clause_count`.
Internally, Elasticsearch takes queries that may be quite short and
rewrites them into potentially many Lucene clauses. The Elasticsearch
default
(https://www.elastic.co/guide/en/elasticsearch/reference/current/search-settings.html)
is to allow up to 1024 clauses.
While the Elasticsearch docs recommend against increasing this setting,
doing so allows us to handle more complex synonym configurations, and is
worth exploring.
Connects https://github.com/OpenTransitTools/trimet-mod-pelias/issues/33

Increase Elasticsearch `max_clause_count`

---

projects/australia/docker-compose.yml
projects/austria/docker-compose.yml
projects/belgium/docker-compose.yml
projects/brazil/docker-compose.yml
projects/france/docker-compose.yml
projects/germany/docker-compose.yml
projects/jamaica/docker-compose.yml
projects/los-angeles-metro/docker-compose.yml
projects/netherlands/docker-compose.yml
projects/new-york-city/docker-compose.yml
projects/north-america/docker-compose.yml
projects/norway/docker-compose.yml
projects/planet/docker-compose.yml
projects/poland/docker-compose.yml
projects/portland-metro/docker-compose.yml
projects/san-jose-metro/docker-compose.yml
projects/singapore/docker-compose.yml
projects/south-africa/docker-compose.yml
projects/south-america/docker-compose.yml
projects/texas/docker-compose.yml

This change should improve the default security  level for the docker containers in pelias-docker.
---
This is a change based on feedback from pelias/docker#254
---
Very little got changed, just port bindings in the docker compose files (for all api's - including pelias).
---
I have already done some testing, this behaved as expected. (I completed a full Australia build and deploy, and it correctly deployed, enabled access to apis on the machine itself, but did not allow network access to them). The API's that were to be exposed had to be explicitly exposed via a mechanism that re-routed the internal requests to external access (reverse proxy in my case).
A standard …

Restricted pelias+deps port exposure to localhost

---

projects/australia/docker-compose.yml
projects/austria/docker-compose.yml
projects/belgium/docker-compose.yml
projects/brazil/docker-compose.yml
projects/france/docker-compose.yml
projects/germany/docker-compose.yml
projects/jamaica/docker-compose.yml
projects/los-angeles-metro/docker-compose.yml
projects/netherlands/docker-compose.yml
projects/new-york-city/docker-compose.yml
projects/north-america/docker-compose.yml
projects/norway/docker-compose.yml
projects/planet/docker-compose.yml
projects/poland/docker-compose.yml
projects/portland-metro/docker-compose.yml
projects/san-jose-metro/docker-compose.yml
projects/singapore/docker-compose.yml
projects/south-africa/docker-compose.yml
projects/south-america/docker-compose.yml
projects/texas/docker-compose.yml

Upgrade the default Elasticsearch image to use version 7.16.1.
This version contains fixes for the log4j 'log4shell' security vulnerability.
Closes https://github.com/pelias/docker/issues/273
Connects https://github.com/pelias/pelias/issues/921

Upgrade Elasticearch to version 7.16.1

---

projects/portland-metro/pelias.json

the file `http://biketownpdx.socialbicycles.com/opendata/station_information.json` is now hosted at `https://gbfs.biketownpdx.com/gbfs/en/station_information.json`

projects: portland-metro CSV URL fix

---

projects/north-america/README.md

Added optional alternative to building and running Valhalla using https://geocode.earth/data/.
Building Valhalla is a lot of work, you can simply download the required files from this website. It is exceptionally more accessible.

Added Alternative to Valhalla

---

projects/portland-metro/pelias.json

as mentioned in the linked issues, two of the data URLs from the `portland-metro` project are broken.
I have uploaded copies from my local machine circa `2022-06-20` until we can find new URLs which point to up-to-date data.
linked: https://github.com/pelias/docker/issues/308
linked: https://github.com/pelias/docker/issues/293
closes https://github.com/pelias/docker/issues/293

portland-metro: fix broken data URLS

---

projects/north-america/README.md

Properly encoded the reference query URL at the bottom of the README.md so that it renders and functions correctly.
Sorry for not squashing but I did this without a cli in the browser.

North America Project README.md link fix

---

README.md
cmd/docker.sh
lib/env.sh

Fixes error like:
line 20: docker-compose: command not found
From: https://docs.docker.com/compose/gettingstarted/
> Compose V1 no longer receives updates and will not be available in new releases of Docker Desktop after June 2023.
---
- update docker compose docs
- refreshed links related to docker compose
- - all the docker commands now delegate to compose_exec (previously only half did)
- `compose_exec` now first tries `docker compose` before falling back to docker-compose`
Alternatively we could just drop docker-compose (v1) support. I confess that I didn't fully test the fallback behavior anyway, and apparently it's no longer supported by docker.
---
Run through any of the example projects that utilize a variety of docker compose commands, e.g. portland-metro
closes …

support modern docker compose

---

projects/portland-metro/test_cases/search_venue.json

Note its sibling test was marked as passing in [627ddaba21d0163036570ee0576cf45c9c1d5ce6](https://github.com/pelias/docker/commit/627ddaba21d0163036570ee0576cf45c9c1d5ce6#diff-820b87478307aee94111365f6b543b9ef578e59040e220566b1afe6be068ff07L29)
I imagine it's pretty challenging to keep all the integration tests up to date, given the churn/fragility of relying on externally edited datasets like openstreetmap and openaddreses.
My understanding, based on #204, is that we don't necessarily expect all the tests in this repository to be accurate, and some are aspirational, but we do want the "full planet" and portland-metro in particular to be accurate.
The "full planet" tests are presumably important for their completeness while portland-metro is presumably important because it serves as a …

This test is not failing (maybe it was previously?)

---

images/elasticsearch/8.12.2-beta/Dockerfile
images/elasticsearch/8.12.2-beta/elasticsearch.yml

this PR adds a [pelias/elasticsearch:8.12.2-beta](https://hub.docker.com/layers/pelias/elasticsearch/8.12.2-beta/images/sha256-4cb6a026bbd3edc18878c0937e73f33f59b0a1ae02591e5c31aa2ebb41cfb384?context=explore) docker image for testing.
cc/ @michaelkirk

add pelias/elasticsearch:8.12.2-beta docker image

---

projects/australia/docker-compose.yml
projects/austria/docker-compose.yml
projects/belgium/docker-compose.yml
projects/brazil/docker-compose.yml
projects/denmark/docker-compose.yml
projects/france/docker-compose.yml
projects/germany/docker-compose.yml
projects/israel/docker-compose.yml
projects/italy/docker-compose.yml
projects/jamaica/docker-compose.yml
projects/las-vegas-metro/docker-compose.yml
projects/lithuania/docker-compose.yml
projects/los-angeles-metro/docker-compose.yml
projects/netherlands/docker-compose.yml
projects/new-york-city/docker-compose.yml
projects/north-america/docker-compose.yml
projects/norway/docker-compose.yml
projects/planet/docker-compose.yml
projects/poland/docker-compose.yml
projects/portland-metro/docker-compose.yml
projects/san-jose-metro/docker-compose.yml
projects/singapore/docker-compose.yml
projects/south-africa/docker-compose.yml
projects/south-america/docker-compose.yml
projects/texas/docker-compose.yml

Happy new year, `v7.17.27` was released 14 January 2025
https://hub.docker.com/layers/pelias/elasticsearch/7.17.27/images/sha256-42acb7033e92ae492a889d2d47a9e3dac7443e03c3287cc91465c7847a149a58
Oneliner:
```bash
grep -l '7\.16\.1' projects/**/docker-compose.yml \
| xargs gsed -i 's/7\.16\.1/7\.17\.27/g'
```
Resolves https://github.com/pelias/docker/issues/366

update elasticsearch to v7.17.27

---

.github/workflows/elasticsearch-image-builder.yml

GitHub is deprecating Ubuntu 20 based runners [on April 1](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/), so we want to be off well before then.
Connects https://github.com/pelias/pelias/issues/951

CI: update Github Action runner Ubuntu versions to 22.04

---

projects/australia/docker-compose.yml

---
The `csv-importer` service is duplicated in the `projects/australia/docker-compose.yml` file, causing errors when running `pelias compose` commands.
---
- Remove the duplicate `csv-importer` service from the `docker-compose.yml` file. 
---
Follow the quick start build script, using the `projects/australia` directory. Verify you are not receiving errors when running the `pelias compose pull` command.

fix(australia): remove duplicate `csv-importer` service from docker-compose.yml

---

cmd/elastic.sh

This PR allows the `indexName` to be configured when executing the `pelias elastic stats` command.
@arnesetzer sorry for all the back-and-forth on this, considering that the scope for this feature is fairly narrow (ie. blue green deployments) I would prefer not to complicate things too much by doing a bunch of refactoring, the `cmd/elastic.sh` script has an established method of overloading the defaults (`ELASTIC_HOST`) so adopting that method allows us to achieve the desired result by simply introducing `ELASTIC_INDEX`.
The ergonomics are maybe not as aesthetically pleasing as using command-line flags, but I don't want to introduce a change where some commands use env vars while others use flags, and this one using a mix of the two.
Again sorry for my poor direction on this, it took me a …

allow configuring `ELASTIC_INDEX` for `elastic_stats` command
